alter table mydb.Address auto_increment=1001;


-- MySQL Script generated by MySQL Workbench
-- Wed Mar 28 23:53:19 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0; 
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
  
-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
  
-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
drop schema `mydb`;
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;
  
-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `User ID` INT NOT NULL,
  `First Name` VARCHAR(45) NULL,
  `Last Name` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Type` VARCHAR(45) NULL,
  `Password` VARCHAR(45) NULL,
  PRIMARY KEY (`User ID`))
ENGINE = InnoDB;
  
  
-- -----------------------------------------------------
-- Table `mydb`.`Type of Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Type of Users` (
  `Type ID` INT NOT NULL,
  `Users_User ID` INT NOT NULL,
  PRIMARY KEY (`Type ID`),
  INDEX `fk_Type of Users_Users1_idx` (`Users_User ID` ASC),
  CONSTRAINT `fk_Type of Users_Users1`
    FOREIGN KEY (`Users_User ID`)
    REFERENCES `mydb`.`Users` (`User ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
  
  
-- -----------------------------------------------------
-- Table `mydb`.`Credit Cards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Credit Cards` (
  `User ID` INT NOT NULL DEFAULT 0,
  `Card ID` BIGINT NOT NULL,
  `Type of card` VARCHAR(45) NULL,
  `Name on card` VARCHAR(45) NULL,
  `Expiration Date` VARCHAR(45) NULL,
  `SecurityCode` INT NOT NULL,
  `Zip` VARCHAR(45) NULL,
  `City` VARCHAR(45) NULL,
  `State` VARCHAR(45) NULL,
  `Country` VARCHAR(45) NULL,
  PRIMARY KEY (`Card ID`))
ENGINE = InnoDB;
  
  
-- -----------------------------------------------------
-- Table `mydb`.`Address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Address` (
  `Street Address 1` VARCHAR(45) NULL,
  `Street Address 2` VARCHAR(45) NULL,
  `Zip` VARCHAR(45) NULL,
  `City` VARCHAR(45) NULL,
  `State` VARCHAR(45) NULL,
  `User ID` INT NULL DEFAULT 0,
  `Country` VARCHAR(45) NULL,
  `Address ID` INT NOT NULL auto_increment,
  PRIMARY KEY (`Address ID`))
ENGINE = InnoDB;
  
  
-- -----------------------------------------------------
-- Table `mydb`.`Booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Booking` (
  `Booking ID` INT NOT NULL,
  `User ID` INT NULL DEFAULT 0,
  `Date` DATETIME NULL,
  `Number of Tickets` VARCHAR(45) NULL,
  `Promocode` VARCHAR(45) NULL,
  `Total` INT NULL,
  `Subtotal` INT NULL,
  `Tax` INT NULL,
  `Status` VARCHAR(45) NULL,
  `Card ID` INT NULL DEFAULT 0,
  `Users_User ID` INT NOT NULL,
  PRIMARY KEY (`Booking ID`),
  INDEX `fk_Booking_Users_idx` (`Users_User ID` ASC),
  CONSTRAINT `fk_Booking_Users`
    FOREIGN KEY (`Users_User ID`)
    REFERENCES `mydb`.`Users` (`User ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
  
  
-- -----------------------------------------------------
-- Table `mydb`.`Promotion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Promotion` (
  `idPromotion` INT NOT NULL,
  `Percentage` VARCHAR(45) NULL,
  `ExpDate` DATETIME NULL,
  `Users_User ID` INT NOT NULL,
  PRIMARY KEY (`idPromotion`),
  INDEX `fk_Promotion_Users1_idx` (`Users_User ID` ASC),
  CONSTRAINT `fk_Promotion_Users1`
    FOREIGN KEY (`Users_User ID`)
    REFERENCES `mydb`.`Users` (`User ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
  
  
-- -----------------------------------------------------
-- Table `mydb`.`Seat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Seat` (
  `Hall ID` INT NOT NULL,
  `code` VARCHAR(45) NULL,
  `SeatNo` INT NOT NULL,
  `Status` VARCHAR(45) NOT NULL,
  `Show ID` INT NOT NULL,
  PRIMARY KEY (`Hall ID`, `SeatNo`, `Show ID`))
ENGINE = InnoDB;
  
  
-- -----------------------------------------------------
-- Table `mydb`.`Ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ticket` (
  `Booking ID` INT NOT NULL DEFAULT 0,
  `TicketID` VARCHAR(45) NOT NULL,
  `Movie ID` INT NULL,
  `ShowTime` DATETIME NULL,
  `Seat` VARCHAR(45) NULL,
  `Age cat` VARCHAR(45) NULL,
  `Purchase Price` INT NULL,
  `Promotion_idPromotion` INT NOT NULL,
  `Seat_Hall ID` INT NOT NULL,
  `Seat_SeatNo` INT NOT NULL,
  `Seat_Show ID` INT NOT NULL,
  PRIMARY KEY (`TicketID`),
  INDEX `fk_Ticket_Promotion1_idx` (`Promotion_idPromotion` ASC),
  INDEX `fk_Ticket_Seat1_idx` (`Seat_Hall ID` ASC, `Seat_SeatNo` ASC, `Seat_Show ID` ASC),
  CONSTRAINT `fk_Ticket_Promotion1`
    FOREIGN KEY (`Promotion_idPromotion`)
    REFERENCES `mydb`.`Promotion` (`idPromotion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ticket_Seat1`
    FOREIGN KEY (`Seat_Hall ID` , `Seat_SeatNo` , `Seat_Show ID`)
    REFERENCES `mydb`.`Seat` (`Hall ID` , `SeatNo` , `Show ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
  
  
-- -----------------------------------------------------
-- Table `mydb`.`Price`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Price` (
  `Age ID` VARCHAR(45) NOT NULL,
  `Price ID` INT NOT NULL,
  `Price` VARCHAR(45) NULL,
  `Code` VARCHAR(45) NULL,
  `Ticket_ID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Price ID`),
  INDEX `fk_Price_Ticket1_idx` (`Ticket_ID` ASC),
  CONSTRAINT `fk_Price_Ticket1`
    FOREIGN KEY (`Ticket_ID`)
    REFERENCES `mydb`.`Ticket` (`TicketID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
  
  
-- -----------------------------------------------------
-- Table `mydb`.`Hall`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Hall` (
  `Hall ID` INT NOT NULL,
  `Total Seats` VARCHAR(45) NULL,
  `Seat_Hall ID` INT NOT NULL,
  `Seat_SeatNo` INT NOT NULL,
  `Seat_Show ID` INT NOT NULL,
  PRIMARY KEY (`Hall ID`),
  INDEX `fk_Hall_Seat1_idx` (`Seat_Hall ID` ASC, `Seat_SeatNo` ASC, `Seat_Show ID` ASC),
  CONSTRAINT `fk_Hall_Seat1`
    FOREIGN KEY (`Seat_Hall ID` , `Seat_SeatNo` , `Seat_Show ID`)
    REFERENCES `mydb`.`Seat` (`Hall ID` , `SeatNo` , `Show ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
  
  
-- -----------------------------------------------------
-- Table `mydb`.`Movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Movie` (
  `Movie ID` INT NOT NULL,
  `Title` VARCHAR(45) NULL,
  `Cast` VARCHAR(45) NULL,
  `Trailer` VARCHAR(45) NULL,
  `Producer` VARCHAR(45) NULL,
  `Trailer Video` VARCHAR(45) NULL,
  `Users_User ID` INT NOT NULL,
  `Ticket_ID` VARCHAR(45) NOT NULL,
  `Hall_Hall ID` INT NOT NULL,
  PRIMARY KEY (`Movie ID`),
  INDEX `fk_Movie_Users1_idx` (`Users_User ID` ASC),
  INDEX `fk_Movie_Ticket1_idx` (`Ticket_ID` ASC),
  INDEX `fk_Movie_Hall1_idx` (`Hall_Hall ID` ASC),
  CONSTRAINT `fk_Movie_Users1`
    FOREIGN KEY (`Users_User ID`)
    REFERENCES `mydb`.`Users` (`User ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movie_Ticket1`
    FOREIGN KEY (`Ticket_ID`)
    REFERENCES `mydb`.`Ticket` (`TicketID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movie_Hall1`
    FOREIGN KEY (`Hall_Hall ID`)
    REFERENCES `mydb`.`Hall` (`Hall ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
  
  
-- -----------------------------------------------------
-- Table `mydb`.`ShowTime`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ShowTime` (
  `Show ID` INT NOT NULL,
  `Hall ID` VARCHAR(45) NULL DEFAULT 0,
  `Movie ID` INT NULL DEFAULT 0,
  `Time` DATETIME NULL,
  `Available Seats` INT NULL,
  PRIMARY KEY (`Show ID`))
ENGINE = InnoDB;
  
  
-- -----------------------------------------------------
-- Table `mydb`.`review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Review` (
  `Review ID` INT NOT NULL,
  `pathToTextFile` VARCHAR(200) NULL,
  `Movie_Movie ID` INT NOT NULL,
  PRIMARY KEY (`Review ID`),
  INDEX `fk_review_Movie1_idx` (`Movie_Movie ID` ASC),
  CONSTRAINT `fk_review_Movie1`
    FOREIGN KEY (`Movie_Movie ID`)
    REFERENCES `mydb`.`Movie` (`Movie ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
  
  
-- -----------------------------------------------------
-- Table `mydb`.`ShowTime_has_Movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ShowTime_has_Movie` (
  `ShowTime_Show ID` INT NOT NULL,
  `Movie_Movie ID` INT NOT NULL,
  PRIMARY KEY (`ShowTime_Show ID`, `Movie_Movie ID`),
  INDEX `fk_ShowTime_has_Movie_Movie1_idx` (`Movie_Movie ID` ASC),
  INDEX `fk_ShowTime_has_Movie_ShowTime1_idx` (`ShowTime_Show ID` ASC),
  CONSTRAINT `fk_ShowTime_has_Movie_ShowTime1`
    FOREIGN KEY (`ShowTime_Show ID`)
    REFERENCES `mydb`.`ShowTime` (`Show ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ShowTime_has_Movie_Movie1`
    FOREIGN KEY (`Movie_Movie ID`)
    REFERENCES `mydb`.`Movie` (`Movie ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
  
  
-- -----------------------------------------------------
-- Table `mydb`.`Users_has_Credit Cards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users_has_Credit Cards` (
  `Users_User ID` INT NOT NULL,
  `Credit Cards_Card ID` BIGINT NOT NULL,
  PRIMARY KEY (`Users_User ID`, `Credit Cards_Card ID`),
  INDEX `fk_Users_has_Credit Cards_Credit Cards1_idx` (`Credit Cards_Card ID` ASC),
  INDEX `fk_Users_has_Credit Cards_Users1_idx` (`Users_User ID` ASC),
  CONSTRAINT `fk_Users_has_Credit Cards_Users1`
    FOREIGN KEY (`Users_User ID`)
    REFERENCES `mydb`.`Users` (`User ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_has_Credit Cards_Credit Cards1`
    FOREIGN KEY (`Credit Cards_Card ID`)
    REFERENCES `mydb`.`Credit Cards` (`Card ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
  
  
-- -----------------------------------------------------
-- Table `mydb`.`Users_has_Address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users_has_Address` (
  `Users_User ID` INT NOT NULL,
  `Address_Address ID` INT NOT NULL,
  PRIMARY KEY (`Users_User ID`, `Address_Address ID`),
  INDEX `fk_Users_has_Address_Address1_idx` (`Address_Address ID` ASC),
  INDEX `fk_Users_has_Address_Users1_idx` (`Users_User ID` ASC),
  CONSTRAINT `fk_Users_has_Address_Users1`
    FOREIGN KEY (`Users_User ID`)
    REFERENCES `mydb`.`Users` (`User ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_has_Address_Address1`
    FOREIGN KEY (`Address_Address ID`)
    REFERENCES `mydb`.`Address` (`Address ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
  
 SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;